tknorris/script.module.urlresolver

lib/urlresolver/plugins/allvid.py
lib/urlresolver/plugins/zerocast.py

trollvid - escaped . in pattern, added additional file scrape and base64 decode(handles missing padding)
allvid.ch - new resolver
zerocast.tv - new resolver

trollvid, allvid, and zerocast

---

lib/urlresolver/plugins/allvid.py
lib/urlresolver/plugins/uptobox.py
lib/urlresolver/plugins/userscloud.py
lib/urlresolver/plugins/zerocast.py

zerocast additional valid_urls added to pattern

updated to use common.XX_USER_AGENT

---

lib/urlresolver/plugins/thevideo.py

- add UA and Referer to resolve Error 400 response
- add catch for potentially unset best_stream_url
- add to pattern

fix thevideo

---

lib/urlresolver/plugins/filmshow.py
lib/urlresolver/plugins/lib/aa_decoder.py
lib/urlresolver/plugins/nowvideo.py
lib/urlresolver/plugins/openload.py
lib/urlresolver/plugins/playhd.py
lib/urlresolver/plugins/videobee.py
lib/urlresolver/plugins/youtube.py

2 new resolvers, filmshow and videobee
fixes to five existing resolvers.

New resolvers

---

addon.xml
lib/urlresolver/plugins/lib/aa_decoder.py

addon.xml: remove whitespace in description, Kodi shows these as characters
aa_decoder: remove unused/unreachable code, readability

addon.xml, aa_decoder: cosmetic

---

lib/urlresolver/plugins/movshare.py

additional embed style included in the pattern

movshare fix

---

lib/urlresolver/plugins/fastplay.py
lib/urlresolver/plugins/nowvideo.py
lib/urlresolver/plugins/playhd.py

1. Newresolver fastplay.sx
2. Additional domain nowvideo.at in nowvideo resolver
3. Indentation fix

one addition, two fixes

---

lib/urlresolver/plugins/lib/aa_decoder.py

try original way

---

lib/urlresolver/plugins/idowatch.py
lib/urlresolver/plugins/letwatch.py
lib/urlresolver/plugins/nowvideo.py
lib/urlresolver/plugins/playu.py

fixes to 
1. idowatch
2. letwatch
3. nowvideo
4. playu

Resolver fixes

---

lib/urlresolver/plugins/ok.py

ok resolver did not return the link of the selected source

OK.ru return selected source

---

lib/urlresolver/plugins/playu.py
lib/urlresolver/plugins/videosky.py

Fixes to playu and watchvideo
videosky new resolver

2 fixes, 1 new resolver

---

lib/urlresolver/common.py
lib/urlresolver/lib/kodi.py
lib/urlresolver/plugins/twitch.py

- add has_addon(addon_id) to kodi, common; return True/False
- requires Twitch add-on
- returns pluginurl for live or vod

twitch resolver

---

lib/urlresolver/plugins/mailru.py

possible issue if cookie return none?

---

lib/urlresolver/plugins/megamp4.py

Speedplay additional domain
MegaMP4 new resolver

One change, one new

---

lib/urlresolver/plugins/watchvideo.py

Additional domains added to resolver

Watchvideo fix

---

lib/urlresolver/plugins/flashx.py
lib/urlresolver/plugins/youlol.py

Flashx resolver rewrite to avoid kodi detection
New resolver Youlol

1 fix, 1 new resolver

---

lib/urlresolver/plugins/vodlocker.py

Vodlocker fix

---

lib/urlresolver/plugins/flashx.py
lib/urlresolver/plugins/indavideo.py
lib/urlresolver/plugins/novamov.py
lib/urlresolver/plugins/rapidvideocom.py
lib/urlresolver/plugins/thevideo.py
lib/urlresolver/plugins/toltsd_fel.py
lib/urlresolver/plugins/watchonline.py
lib/urlresolver/plugins/youwatch.py

Added new resolvers:
-indavideo
-watchonlie
-toltsd-fel
Fixed resolvers: 
-youwatch
Updated resolvers: 
-novamov
-rapidvideo
-flashx

added indavideo, watchonline, toltsd-fel/fixed youwatch, novamov

---

lib/urlresolver/plugins/flashx.py

Fix FlashX resolver to pick the dynamic check url

FlashX fix

---

lib/urlresolver/plugins/fastplay.py
lib/urlresolver/plugins/vidmad.py

fastplay additional domain
vidmad new resolver

1 fix 1 new resolver

---

lib/urlresolver/plugins/ol_gmu.py

2 commits too many, Github software acting strange :)

Openload fix

---

lib/urlresolver/plugins/vidmad.py

Update vidmad resolver

---

lib/urlresolver/plugins/flashx.py
lib/urlresolver/plugins/powerwatch.py
lib/urlresolver/plugins/watchpass.py

Just saw that you also have fixed flashx, but your fix isn't working for me. I needed to add a call to 'http://www.flashx.tv/coding.js?cd=' to make it working again.

Some fixes + new site

---

lib/urlresolver/plugins/flashx.py

Just a minor bugfix because some users had problems

[flashx] increased sleeping time

---

lib/urlresolver/plugins/ani-stream.py

Add Resolver for http://www.ani-stream.com/

Add Ani-Stream Resolver

---

lib/urlresolver/plugins/youtube.py

Because the regex support it ;)

support "youtube-nocookie.com"

---

lib/urlresolver/plugins/flashx.py

Donno why but i have to ingress the sleep because some links seems to be broken with 5500

fix flashX again

---

lib/urlresolver/plugins/putload.py
lib/urlresolver/plugins/speedplay.py

1 new resolver
1 additional domain in existing resolver

Additional resolver

---

lib/urlresolver/plugins/lib/helpers.py
lib/urlresolver/plugins/novamov.py
lib/urlresolver/plugins/playhd.py
lib/urlresolver/plugins/putload.py
lib/urlresolver/plugins/uptobox.py
lib/urlresolver/plugins/vidbull.py

- use data-res (720p/480p etc) for label if exists, or type (mp4/flv etc) as fallback
- also updates some resolvers that benefit

add parse_html5_source_list to helpers

---

lib/urlresolver/plugins/flashx.py

lets count the hours^^
*EDIT*
Party PR 200!! :)

fix flashX

---

lib/urlresolver/plugins/flashx.py

update flashX #2

---

lib/urlresolver/plugins/flashx.py

seems like they want the cat and mouse game. They obfuscated the api-js

update flashX.tv #1

---

lib/urlresolver/plugins/flashx.py

update flashX.tv #2

---

lib/urlresolver/plugins/flashx.py

small note for u:
`<div style="visibility:hidden">DEAR KODI. WE COULD DO THIS ALL THE DAY! WE WILL DO THIS THE NEXT 50 YEARS! WE HAVE TIME AND WE HAVE FUN!</div>`

update flashX.tv #10

---

lib/urlresolver/plugins/mersalaayitten.py

Mersalaayitten fix

---

lib/urlresolver/plugins/vidabc.py

second attempt PR :) 
-add generic class
-tested link: http://vidabc.com/embed-pxdwsev4tvcg.html

Add vidabc.com

---

lib/urlresolver/plugins/animeportal.py

sry for this PR. Its work even with the slash. But im not 100% sure if maybe some python versions have a problem with this.

fix anime-portal

---

lib/urlresolver/plugins/vidhos.py

may you merge this site too plz

add vidhos

---

addon.xml
lib/urlresolver/plugins/youtube.py

- return resolved url instead of plugin url when possible

update youtube resolver

---

lib/urlresolver/plugins/__generic_resolver__.py

So it also match the template that is used for get_url: 'http://{host}/embed-{media_id}.html'

change sample pattern

---

lib/urlresolver/plugins/datoporn.py

Support for resolving links from datoporn.com/dato.porn

Add DatoPorn to Resolver

---

lib/urlresolver/plugins/lib/helpers.py

fix streamcloud and anistream and maybe some more ^^

allow "file" as single property in scrape_sources

---

lib/urlresolver/hmf.py

optional, not sure if this would break anything

prepend "http:" if needed

---

lib/urlresolver/plugins/goflicker.py
lib/urlresolver/plugins/speedwatch.py
lib/urlresolver/plugins/tunepk.py
lib/urlresolver/plugins/tvlogy.py
lib/urlresolver/plugins/videoraj.py

Fixes to
VideoRaj, TunePK
New Resolvers
GoFlicker, SpeedWatch and TVLogy

2 Fixes 3 New Resolvers
